export type AppLanguage = "en" | "zh" | "hokkien" | "yue" | "ta" | "ms";

export const LANGUAGE_OPTIONS: { id: AppLanguage; label: string }[] = [
  { id: "en", label: "English" },
  { id: "zh", label: "华语 (Mandarin)" },
  { id: "hokkien", label: "闽南话 (Hokkien)" },
  { id: "yue", label: "粤语 (Cantonese)" },
  { id: "ta", label: "தமிழ் (Tamil)" },
  { id: "ms", label: "Melayu" },
];

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.medications": "Medications",
    "nav.askMei": "Ask Mei",
    "nav.notifications": "Notifications",
    "nav.settings": "Settings",
    "header.hello": "Hello, {name}!",
    "home.today": "Today",
    "home.scheduled": "Scheduled",
    "home.comingUp": "Coming up",
    "home.taken": "taken",
    "home.takenAt": "Taken at {time}",
    "home.vagueTimeNote": "{note} · around {clock}",
    "home.morning": "Morning",
    "home.afternoon": "Afternoon",
    "home.evening": "Evening",
    "home.night": "Night",
    "home.iTookIt": "I Took It ✓",
    "home.markTaken": "Mark as taken",
    "home.whatTime": "What time did you take it?",
    "home.justNow": "Just now",
    "home.confirm": "Confirm",
    "home.recorded": "Recorded! Well done 🌟",
    "home.now": "Now",
    "home.refillNeeded": "Refill needed soon",
    "home.noSchedule": "No medications scheduled.",
    "home.takeAsDirected": "Take as directed by your doctor.",
    "home.timesShownIn": "Times shown in {tz}",
    "home.tapToView": "Tap to view",
    "home.hide": "Hide",
    "home.scheduledFor": "Scheduled for {clock}",
    "home.willLogAs": "You'll log it as {time}",
    "prescription.count": "{count} medications",
    "prescription.add": "Add refill / prescription",
    "prescription.empty": "No medicines added yet — tap \"Add refill / prescription\" above to get started.",
    "prescription.supply": "Supply remaining",
    "prescription.past": "Past medications",
    "prescription.disclaimer": "Always take medications exactly as prescribed. Never stop or change your dose without checking with your doctor first.",
    "prescription.daysLeftBadge": "{days}d left",
    "prescription.forPurpose": "For {purpose}",
    "prescription.howToUseEyeDrops": "How to use eye drops",
    "prescription.supplyOfTotal": "{days}/30 days",
    "prescription.stepByStepGuide": "Step-by-step guide",
    "prescription.eyeDropsAlt": "Eye drops demonstration",
    "prescription.watchHowToUse": "Watch: How to use eye drops",
    "prescription.videoGuideLength": "Video guide · 2 min",
    "notifications.header": "Messages from your family and care team",
    "notifications.empty": "No messages yet from your caregiver.",
    "settings.voiceAndLanguage": "Voice & Language",
    "settings.readAloud": "Read Aloud",
    "settings.readAloudDesc": "Mei reads her replies out loud",
    "settings.language": "Language",
    "settings.languageDesc": "Used throughout the app, including Mei's replies",
    "settings.yourProfile": "Your Profile",
    "settings.age": "Age",
    "settings.dob": "Date of birth",
    "settings.gender": "Gender",
    "settings.weightKg": "Weight (kg)",
    "settings.heightCm": "Height (cm)",
    "settings.medicalConditions": "Medical conditions",
    "settings.generalAllergies": "General allergies",
    "settings.medicationAllergies": "Medication allergies",
    "settings.mealsSleep": "Meals & sleep",
    "settings.saveChanges": "Save changes",
    "settings.saving": "Saving…",
    "settings.saved": "Saved!",
    "settings.accessibility": "Accessibility",
    "settings.textSize": "Text Size",
    "settings.textSizeDesc": "Drag to make text smaller or larger",
    "settings.highContrast": "High Contrast",
    "settings.highContrastDesc": "Bolder colours and stronger outlines for easier reading",
    "settings.colourBlindMode": "Colour Blind Mode",
    "settings.colourBlindDesc": "Uses pill shape, markings, and text — not colour — to identify each medication",
    "settings.medicationDescriptions": "Your medication descriptions",
    "settings.reminders": "Reminders",
    "settings.medicationReminders": "Medication Reminders",
    "settings.medicationRemindersDesc": "Alert when it's time to take medication",
    "settings.emergencyContact": "Emergency Contact",
    "settings.switchToCaregiver": "Switch to Caregiver Mode",
    "settings.signOut": "Sign out",
    "settings.account": "Account",
    "settings.editProfile": "Edit profile",
    "settings.missedDoseAlerts": "Missed dose alerts",
    "settings.missedDoseAlertsDesc": "Immediate push notification",
    "settings.refillReminders": "Refill reminders",
    "settings.refillRemindersDesc": "Alert when supply drops below {days} days",
    "settings.weeklyAiSummary": "Weekly AI summary",
    "settings.weeklyAiSummaryDesc": "Every Monday morning",
    "settings.alertWhenBelow": "Alert when below",
    "settings.careTeamAccess": "Care Team Access",
    "settings.addCareTeamMember": "Add care team member",
    "settings.privacySecurity": "Privacy & Security",
    "settings.dataEncryption": "Data encryption",
    "settings.dataEncryptionDesc": "End-to-end encrypted",
    "settings.pdpaCompliance": "PDPA compliance",
    "settings.pdpaComplianceDesc": "Singapore PDPA 2012",
    "settings.auditLog": "Audit log",
    "settings.auditLogDesc": "All access events recorded",
    "settings.switchToElderly": "Switch to Elderly Mode",
    "settings.footer": "Made with care in Singapore",
    "ai.chatTab": "Chat with Mei",
    "ai.doctorTab": "Ask Doctor",
    "ai.quickHelp": "Quick help",
    "ai.helpSetup": "Help me set up",
    "ai.languageVoice": "Language & voice",
    "ai.speaking": "Speaking",
    "dashboard.dosesTaken": "{taken} of {total} doses taken",
    "dashboard.missedDoseAlert": "Missed dose alert",
    "dashboard.wasDueAt": "{name} {dose} — was due at {time}",
    "dashboard.remind": "Remind",
    "dashboard.daysRemainingOrderSoon": "{days} days remaining · Order soon",
    "dashboard.quickActions": "Quick Actions",
    "common.home": "Home",
    "common.schedule": "Schedule",
    "common.askMei": "Ask Mei",
    "common.patient": "Patient",
    "common.settings": "Settings",
    "common.today": "Today",
    "common.daily": "Daily",
    "common.weekly": "Weekly",
    "common.viewSchedule": "View Schedule",
    "common.checkSchedule": "Check Schedule",
    "common.sendReminder": "Send Reminder",
    "common.leaveNote": "Leave Note",
    "common.emergency": "Emergency",
    "common.addPrescription": "Add prescription",
    "common.edit": "Edit",
    "common.add": "+ Add",
    "common.fullName": "Full name",
    "common.roleExample": "Role (e.g. Doctor, Daughter, Helper)",
    "common.removeMedication": "Remove medication",
    "common.medicalConditions": "Medical Conditions",
    "common.knownAllergies": "Known Allergies",
    "common.currentMedications": "Current Medications",
    "common.pastMedications": "Past Medications",
    "common.relationAge": "{relation} · Age {age}",
    "common.bloodType": "Blood Type {type}",
    "common.conditionsCount": "{count} Conditions",
    "common.medicationsCount": "{count} Medications",
    "common.emergencyContacts": "Emergency Contacts",
    "common.addOne": "Add one",
    "common.noConditionsRecorded": "No conditions recorded.",
    "common.noAllergiesRecorded": "No allergies recorded.",
    "common.daysOfSupplyLeft": "{count} days of supply left",
    "common.notDue": "Not due",
    "common.taken": "Taken",
    "common.missed": "Missed",
    "common.upcoming": "Upcoming",
    "common.dismiss": "Dismiss",
    "common.requested": "Requested",
    "common.allClear": "All clear",
    "common.noPendingNotifications": "No pending notifications.",
    "common.callPatient": "Call Patient",
    "common.orderRefill": "Order Refill",
    "common.weeklySummary": "Weekly Summary",
    "common.travelMode": "Travel Mode",
    "common.askMeiPlaceholder": "Ask Mei about this patient...",
    "common.signIn": "Sign in",
    "common.welcomeBack": "Welcome back",
    "common.signInToContinue": "Sign in to continue to Dosewise.",
    "common.dontHaveAccount": "Don't have an account? Get started",
    "common.getStarted": "Get started",
    "common.alreadyHaveAccount": "I already have an account",
    "common.whoAreYouUsing": "Who are you using\nDosewise for today?",
    "common.forLovedOne": "For a Loved One",
    "common.forMyself": "For Myself",
    "common.modeHint": "We'll tailor your experience based\non how you'd like to use the app.",
    "common.switchModesHint": "You can switch modes anytime in Settings.",
    "common.howSetUp": "How would you like\nto set up your profile?",
    "common.setUpHint": "Pick whichever feels easier — you can always add more details later.",
    "common.healthHub": "Sign in with HealthHub",
    "common.healthHubComingSoon": "Coming soon",
    "common.guidedSetup": "Answer a few simple questions",
    "common.setupMinutes": "This should only take a few minutes.",
  },
  zh: {
    "nav.home": "首页",
    "nav.medications": "药物",
    "nav.askMei": "问Mei",
    "nav.notifications": "通知",
    "nav.settings": "设置",
    "header.hello": "你好，{name}！",
    "home.today": "今天",
    "home.scheduled": "已安排",
    "home.comingUp": "即将到来",
    "home.taken": "已服用",
    "home.takenAt": "已于 {time} 服用",
    "home.vagueTimeNote": "{note} · 大约 {clock}",
    "home.morning": "早上",
    "home.afternoon": "下午",
    "home.evening": "傍晚",
    "home.night": "晚上",
    "home.iTookIt": "我已经服用了 ✓",
    "home.markTaken": "标记为已服用",
    "home.whatTime": "你是什么时间服用的？",
    "home.justNow": "刚刚",
    "home.confirm": "确认",
    "home.recorded": "已记录！做得很好 🌟",
    "home.now": "现在",
    "home.refillNeeded": "药量快用完",
    "home.noSchedule": "没有安排的药物。",
    "home.takeAsDirected": "请遵照医生指示服用。",
    "home.timesShownIn": "时间以 {tz} 显示",
    "home.tapToView": "点击查看",
    "home.hide": "隐藏",
    "home.scheduledFor": "预定于 {clock}",
    "home.willLogAs": "将记录为 {time}",
    "prescription.count": "{count} 种药物",
    "prescription.add": "添加续药 / 处方",
    "prescription.empty": "还没有药物 — 点击上方的“添加续药 / 处方”开始。",
    "prescription.supply": "剩余供应",
    "prescription.past": "过去服用过的药物",
    "prescription.disclaimer": "请严格按照医生开的药方服药。不要自行停药或更改剂量。",
    "prescription.daysLeftBadge": "还剩 {days} 天",
    "prescription.forPurpose": "用于{purpose}",
    "prescription.howToUseEyeDrops": "如何使用眼药水",
    "prescription.supplyOfTotal": "{days}/30 天",
    "prescription.stepByStepGuide": "分步指南",
    "prescription.eyeDropsAlt": "滴眼药水示范",
    "prescription.watchHowToUse": "观看：如何使用眼药水",
    "prescription.videoGuideLength": "视频指南 · 2 分钟",
    "notifications.header": "来自家人和护理团队的消息",
    "notifications.empty": "还没有护理人员发来的消息。",
    "settings.voiceAndLanguage": "语音与语言",
    "settings.readAloud": "朗读回复",
    "settings.readAloudDesc": "Mei 会把回复读出来",
    "settings.language": "语言",
    "settings.languageDesc": "整个应用程序中使用，包括 Mei 的回复",
    "settings.yourProfile": "您的资料",
    "settings.age": "年龄",
    "settings.dob": "出生日期",
    "settings.gender": "性别",
    "settings.weightKg": "体重 (kg)",
    "settings.heightCm": "身高 (cm)",
    "settings.medicalConditions": "医疗状况",
    "settings.generalAllergies": "一般过敏",
    "settings.medicationAllergies": "药物过敏",
    "settings.mealsSleep": "饮食与睡眠",
    "settings.saveChanges": "保存更改",
    "settings.saving": "正在保存…",
    "settings.saved": "已保存！",
    "settings.accessibility": "无障碍",
    "settings.textSize": "文字大小",
    "settings.textSizeDesc": "拖动以缩小或放大文字",
    "settings.highContrast": "高对比度",
    "settings.highContrastDesc": "更大胆的颜色和更清晰的轮廓，方便阅读",
    "settings.colourBlindMode": "色盲模式",
    "settings.colourBlindDesc": "使用药丸形状、标记和文字，而不是颜色来识别每种药物",
    "settings.medicationDescriptions": "您的药物说明",
    "settings.reminders": "提醒",
    "settings.medicationReminders": "药物提醒",
    "settings.medicationRemindersDesc": "到药物服用时间时提醒",
    "settings.emergencyContact": "紧急联系人",
    "settings.switchToCaregiver": "切换到照护者模式",
    "settings.signOut": "退出登录",
    "settings.account": "帐户",
    "settings.editProfile": "编辑资料",
    "settings.missedDoseAlerts": "漏服提醒",
    "settings.missedDoseAlertsDesc": "即时推送通知",
    "settings.refillReminders": "补药提醒",
    "settings.refillRemindersDesc": "库存低于 {days} 天时提醒",
    "settings.weeklyAiSummary": "每周 AI 总结",
    "settings.weeklyAiSummaryDesc": "每周一早上",
    "settings.alertWhenBelow": "低于此天数时提醒",
    "settings.careTeamAccess": "护理团队权限",
    "settings.addCareTeamMember": "添加护理团队成员",
    "settings.privacySecurity": "隐私与安全",
    "settings.dataEncryption": "数据加密",
    "settings.dataEncryptionDesc": "端到端加密",
    "settings.pdpaCompliance": "符合 PDPA 规定",
    "settings.pdpaComplianceDesc": "新加坡 2012 年 PDPA",
    "settings.auditLog": "审计日志",
    "settings.auditLogDesc": "所有访问事件均被记录",
    "settings.switchToElderly": "切换到长者模式",
    "settings.footer": "在新加坡用心制作",
    "ai.chatTab": "与Mei聊天",
    "ai.doctorTab": "问医生",
    "ai.quickHelp": "快速帮助",
    "ai.helpSetup": "帮我设置",
    "ai.languageVoice": "语言与语音",
    "ai.speaking": "正在说",
    "dashboard.dosesTaken": "已服用 {taken} / {total} 剂",
    "dashboard.missedDoseAlert": "漏服提醒",
    "dashboard.wasDueAt": "{name} {dose} — 应于 {time} 服用",
    "dashboard.remind": "提醒",
    "dashboard.daysRemainingOrderSoon": "还剩 {days} 天 · 请尽快订购",
    "dashboard.quickActions": "快捷操作",
    "common.home": "首页",
    "common.schedule": "日程",
    "common.askMei": "问Mei",
    "common.patient": "患者",
    "common.settings": "设置",
    "common.today": "今天",
    "common.daily": "每日",
    "common.weekly": "每周",
    "common.viewSchedule": "查看日程",
    "common.checkSchedule": "查看日程",
    "common.sendReminder": "发送提醒",
    "common.leaveNote": "留言",
    "common.emergency": "紧急情况",
    "common.addPrescription": "添加处方",
    "common.edit": "编辑",
    "common.add": "+ 添加",
    "common.fullName": "姓名",
    "common.roleExample": "角色（例如：医生、女儿、看护）",
    "common.removeMedication": "移除药物",
    "common.medicalConditions": "医疗状况",
    "common.knownAllergies": "已知过敏",
    "common.currentMedications": "当前药物",
    "common.pastMedications": "既往药物",
    "common.relationAge": "{relation} · {age} 岁",
    "common.bloodType": "血型 {type}",
    "common.conditionsCount": "{count} 项病情",
    "common.medicationsCount": "{count} 种药物",
    "common.emergencyContacts": "紧急联系人",
    "common.addOne": "添加一个",
    "common.noConditionsRecorded": "尚未记录病情。",
    "common.noAllergiesRecorded": "尚未记录过敏。",
    "common.daysOfSupplyLeft": "还剩 {count} 天补给",
    "common.notDue": "不在本期",
    "common.taken": "已服用",
    "common.missed": "漏服",
    "common.upcoming": "即将到来",
    "common.dismiss": "关闭",
    "common.requested": "已请求",
    "common.allClear": "一切正常",
    "common.noPendingNotifications": "没有待处理通知。",
    "common.callPatient": "联系患者",
    "common.orderRefill": "补药",
    "common.weeklySummary": "每周总结",
    "common.travelMode": "旅行模式",
    "common.askMeiPlaceholder": "向Mei询问关于这个患者的信息...",
    "common.signIn": "登录",
    "common.welcomeBack": "欢迎回来",
    "common.signInToContinue": "登录以继续使用 Dosewise。",
    "common.dontHaveAccount": "还没有账号？开始使用",
    "common.getStarted": "开始使用",
    "common.alreadyHaveAccount": "我已经有账号",
    "common.whoAreYouUsing": "你今天是\n为谁使用 Dosewise？",
    "common.forLovedOne": "为亲友使用",
    "common.forMyself": "为自己使用",
    "common.modeHint": "我们会根据你希望如何使用应用来定制体验。",
    "common.switchModesHint": "你可以随时在设置中切换模式。",
    "common.howSetUp": "你想如何\n设置你的资料？",
    "common.setUpHint": "选择任何一种方式都可以，之后也可以补充更多信息。",
    "common.healthHub": "使用 HealthHub 登录",
    "common.healthHubComingSoon": "即将推出",
    "common.guidedSetup": "回答几个简单的问题",
    "common.setupMinutes": "这只需要几分钟。",
  },
  hokkien: {
    "nav.home": "厝內",
    "nav.medications": "藥",
    "nav.askMei": "問Mei",
    "nav.notifications": "通知",
    "nav.settings": "設定",
    "header.hello": "你好，{name}！",
    "home.today": "今仔日",
    "home.scheduled": "已排好",
    "home.comingUp": "緊欲來",
    "home.taken": "已食",
    "home.takenAt": "佇 {time} 食矣",
    "home.vagueTimeNote": "{note} · 大約 {clock}",
    "home.morning": "早起",
    "home.afternoon": "下晡",
    "home.evening": "欲暗仔",
    "home.night": "暗時",
    "home.iTookIt": "我已經食了 ✓",
    "home.markTaken": "標做已食",
    "home.whatTime": "你是啥時食的？",
    "home.justNow": "才無外久",
    "home.confirm": "確認",
    "home.recorded": "已記好！真好 🌟",
    "home.now": "現在",
    "home.refillNeeded": "藥差不多無矣",
    "home.noSchedule": "無安排的藥。",
    "home.takeAsDirected": "請照醫生的指示食藥。",
    "home.timesShownIn": "時間用 {tz} 顯示",
    "home.tapToView": "㧒一下看",
    "home.hide": "囥起來",
    "home.scheduledFor": "排佇 {clock}",
    "home.willLogAs": "會記做 {time}",
    "prescription.count": "{count} 種藥",
    "prescription.add": "加續藥 / 處方",
    "prescription.empty": "猶未有藥 — 請拍上方「加續藥 / 處方」開始。",
    "prescription.supply": "剩餘藥量",
    "prescription.past": "以前食過的藥",
    "prescription.disclaimer": "請照醫生囑咐食藥。莫好家己停藥或改藥量。",
    "prescription.daysLeftBadge": "賰 {days} 工",
    "prescription.forPurpose": "用來{purpose}",
    "prescription.howToUseEyeDrops": "按怎用目藥水",
    "prescription.supplyOfTotal": "{days}/30 工",
    "prescription.stepByStepGuide": "一步一步教你",
    "prescription.eyeDropsAlt": "點目藥水示範",
    "prescription.watchHowToUse": "看：按怎用目藥水",
    "prescription.videoGuideLength": "影片教學 · 2 分鐘",
    "notifications.header": "家人佮照顧團隊的訊息",
    "notifications.empty": "猶未有照顧者送來的訊息。",
    "settings.voiceAndLanguage": "語音佮話語",
    "settings.readAloud": "讀出來",
    "settings.readAloudDesc": "Mei 會唸出伊的回覆",
    "settings.language": "話語",
    "settings.languageDesc": "規个 app 攏用這个話語，包括 Mei 的回答",
    "settings.yourProfile": "你的資料",
    "settings.age": "歲數",
    "settings.dob": "出世日期",
    "settings.gender": "性別",
    "settings.weightKg": "體重 (kg)",
    "settings.heightCm": "身懸 (cm)",
    "settings.medicalConditions": "病情",
    "settings.generalAllergies": "一般過敏",
    "settings.medicationAllergies": "藥物過敏",
    "settings.mealsSleep": "食飯佮睏眠",
    "settings.saveChanges": "存起來",
    "settings.saving": "咧存…",
    "settings.saved": "已經存好矣！",
    "settings.accessibility": "無障礙",
    "settings.textSize": "字體大細",
    "settings.textSizeDesc": "㧒予字較細抑是較大",
    "settings.highContrast": "高對比",
    "settings.highContrastDesc": "較深的色佮較清楚的框，較好看",
    "settings.colourBlindMode": "色盲模式",
    "settings.colourBlindDesc": "用藥丸的形、記號佮文字，毋是色水，來認每一種藥",
    "settings.medicationDescriptions": "你的藥物說明",
    "settings.reminders": "提醒",
    "settings.medicationReminders": "藥物提醒",
    "settings.medicationRemindersDesc": "到食藥的時陣就提醒你",
    "settings.emergencyContact": "緊急聯絡人",
    "settings.switchToCaregiver": "換做照顧者模式",
    "settings.signOut": "登出",
    "settings.account": "帳戶",
    "settings.editProfile": "改資料",
    "settings.missedDoseAlerts": "漏食提醒",
    "settings.missedDoseAlertsDesc": "隨時推播通知",
    "settings.refillReminders": "續藥提醒",
    "settings.refillRemindersDesc": "藥賰無夠 {days} 工就提醒",
    "settings.weeklyAiSummary": "逐禮拜的 AI 總結",
    "settings.weeklyAiSummaryDesc": "逐禮拜一早起",
    "settings.alertWhenBelow": "低過遮的工數就提醒",
    "settings.careTeamAccess": "照顧團隊權限",
    "settings.addCareTeamMember": "加照顧團隊的人",
    "settings.privacySecurity": "隱私佮安全",
    "settings.dataEncryption": "資料加密",
    "settings.dataEncryptionDesc": "頭尾加密",
    "settings.pdpaCompliance": "照 PDPA 規定",
    "settings.pdpaComplianceDesc": "新加坡 2012 年 PDPA",
    "settings.auditLog": "稽核紀錄",
    "settings.auditLogDesc": "所有的存取代誌攏有記",
    "settings.switchToElderly": "換做老人模式",
    "settings.footer": "佇新加坡用心做的",
    "ai.chatTab": "跟Mei講",
    "ai.doctorTab": "問醫生",
    "ai.quickHelp": "緊急幫助",
    "ai.helpSetup": "幫我設定",
    "ai.languageVoice": "話語佮語音",
    "ai.speaking": "咧講",
    "dashboard.dosesTaken": "已經食 {taken} / {total} 劑",
    "dashboard.missedDoseAlert": "漏食提醒",
    "dashboard.wasDueAt": "{name} {dose} — 本底愛佇 {time} 食",
    "dashboard.remind": "提醒",
    "dashboard.daysRemainingOrderSoon": "賰 {days} 工 · 緊叫貨",
    "dashboard.quickActions": "緊急功能",
    "common.home": "厝內",
    "common.schedule": "排程",
    "common.askMei": "問Mei",
    "common.patient": "病人",
    "common.settings": "設定",
    "common.today": "今仔日",
    "common.daily": "逐日",
    "common.weekly": "逐禮拜",
    "common.viewSchedule": "看排程",
    "common.checkSchedule": "看排程",
    "common.sendReminder": "送提醒",
    "common.leaveNote": "留話",
    "common.emergency": "緊急",
    "common.addPrescription": "加處方",
    "common.edit": "改",
    "common.add": "+ 加",
    "common.fullName": "姓名",
    "common.roleExample": "角色（比如：醫生、查某囝、幫傭）",
    "common.removeMedication": "除去藥",
    "common.medicalConditions": "病情",
    "common.knownAllergies": "知影的過敏",
    "common.currentMedications": "現此時的藥",
    "common.pastMedications": "以前的藥",
    "common.relationAge": "{relation} · {age} 歲",
    "common.bloodType": "血型 {type}",
    "common.conditionsCount": "{count} 項病情",
    "common.medicationsCount": "{count} 種藥",
    "common.emergencyContacts": "緊急聯絡人",
    "common.addOne": "加一項",
    "common.noConditionsRecorded": "猶未記錄病情。",
    "common.noAllergiesRecorded": "猶未記錄過敏。",
    "common.daysOfSupplyLeft": "猶剩 {count} 工藥",
    "common.notDue": "這陣無著",
    "common.taken": "已經食矣",
    "common.missed": "漏食",
    "common.upcoming": "緊欲來",
    "common.dismiss": "收掉",
    "common.requested": "已經叫矣",
    "common.allClear": "攏無事",
    "common.noPendingNotifications": "無未處理的通知。",
    "common.callPatient": "打給病人",
    "common.orderRefill": "叫續藥",
    "common.weeklySummary": "逐禮拜總結",
    "common.travelMode": "旅行模式",
    "common.askMeiPlaceholder": "問Mei有關這個病人的事情...",
    "common.signIn": "登入",
    "common.welcomeBack": "歡迎返來",
    "common.signInToContinue": "登入來續用 Dosewise。",
    "common.dontHaveAccount": "猶未有帳號？開始用",
    "common.getStarted": "開始用",
    "common.alreadyHaveAccount": "我本來就有帳號",
    "common.whoAreYouUsing": "你今仔日是\n為啥人用 Dosewise？",
    "common.forLovedOne": "為親情的人",
    "common.forMyself": "為家己",
    "common.modeHint": "阮會照你想按怎用這个 app 來調整體驗。",
    "common.switchModesHint": "你隨時會使佇設定內切換模式。",
    "common.howSetUp": "你想按怎\n設定你的資料？",
    "common.setUpHint": "揀一種就好，之後猶會使加更多資料。",
    "common.healthHub": "用 HealthHub 登入",
    "common.healthHubComingSoon": "即將開始",
    "common.guidedSetup": "回答幾个簡單問題",
    "common.setupMinutes": "這只需要幾分鐘。",
  },
  yue: {
    "nav.home": "首頁",
    "nav.medications": "藥物",
    "nav.askMei": "問Mei",
    "nav.notifications": "通知",
    "nav.settings": "設定",
    "header.hello": "你好，{name}！",
    "home.today": "今日",
    "home.scheduled": "已安排",
    "home.comingUp": "即將到嚟",
    "home.taken": "已服用",
    "home.takenAt": "已喺 {time} 服用",
    "home.vagueTimeNote": "{note} · 大約 {clock}",
    "home.morning": "朝早",
    "home.afternoon": "下畫",
    "home.evening": "傍晚",
    "home.night": "夜晚",
    "home.iTookIt": "我已經食咗 ✓",
    "home.markTaken": "標記為已服用",
    "home.whatTime": "你係咩時間服用嘅？",
    "home.justNow": "剛先",
    "home.confirm": "確認",
    "home.recorded": "已記錄！做得好 🌟",
    "home.now": "而家",
    "home.refillNeeded": "藥快用完",
    "home.noSchedule": "冇安排嘅藥物。",
    "home.takeAsDirected": "請按照醫生指示服用。",
    "home.timesShownIn": "時間以 {tz} 顯示",
    "home.tapToView": "撳一下睇",
    "home.hide": "隱藏",
    "home.scheduledFor": "預定喺 {clock}",
    "home.willLogAs": "會記錄為 {time}",
    "prescription.count": "{count} 種藥物",
    "prescription.add": "加續藥 / 處方",
    "prescription.empty": "重未有藥物 — 請撳上方「加續藥 / 處方」開始。",
    "prescription.supply": "剩餘藥量",
    "prescription.past": "以前食過嘅藥物",
    "prescription.disclaimer": "請照醫生處方食藥。唔好自行停藥或改藥量。",
    "prescription.daysLeftBadge": "剩 {days} 日",
    "prescription.forPurpose": "用嚟{purpose}",
    "prescription.howToUseEyeDrops": "點樣用眼藥水",
    "prescription.supplyOfTotal": "{days}/30 日",
    "prescription.stepByStepGuide": "逐步指南",
    "prescription.eyeDropsAlt": "滴眼藥水示範",
    "prescription.watchHowToUse": "睇：點樣用眼藥水",
    "prescription.videoGuideLength": "影片指南 · 2 分鐘",
    "notifications.header": "來自屋企人同護理團隊嘅訊息",
    "notifications.empty": "重未有護理人員嘅訊息。",
    "settings.voiceAndLanguage": "語音同語言",
    "settings.readAloud": "朗讀回覆",
    "settings.readAloudDesc": "Mei 會將回覆讀出嚟",
    "settings.language": "語言",
    "settings.languageDesc": "成個 app 都會用呢種語言，包括 Mei 嘅回覆",
    "settings.yourProfile": "你嘅資料",
    "settings.age": "年齡",
    "settings.dob": "出生日期",
    "settings.gender": "性別",
    "settings.weightKg": "體重 (kg)",
    "settings.heightCm": "身高 (cm)",
    "settings.medicalConditions": "病情",
    "settings.generalAllergies": "一般過敏",
    "settings.medicationAllergies": "藥物過敏",
    "settings.mealsSleep": "膳食同瞓覺時間",
    "settings.saveChanges": "儲存更改",
    "settings.saving": "儲存緊…",
    "settings.saved": "已儲存！",
    "settings.accessibility": "無障礙",
    "settings.textSize": "文字大小",
    "settings.textSizeDesc": "拖動嚟縮細或放大文字",
    "settings.highContrast": "高對比",
    "settings.highContrastDesc": "更鮮明嘅顏色同更清晰嘅框線，方便閱讀",
    "settings.colourBlindMode": "色盲模式",
    "settings.colourBlindDesc": "用藥丸形狀、標記同文字，唔係顏色，嚟辨認每種藥物",
    "settings.medicationDescriptions": "你嘅藥物說明",
    "settings.reminders": "提醒",
    "settings.medicationReminders": "藥物提醒",
    "settings.medicationRemindersDesc": "到食藥時間就提醒",
    "settings.emergencyContact": "緊急聯絡人",
    "settings.switchToCaregiver": "切換去照顧者模式",
    "settings.signOut": "登出",
    "settings.account": "帳戶",
    "settings.editProfile": "編輯資料",
    "settings.missedDoseAlerts": "漏服提醒",
    "settings.missedDoseAlertsDesc": "即時推送通知",
    "settings.refillReminders": "補藥提醒",
    "settings.refillRemindersDesc": "存量少過 {days} 日就提醒",
    "settings.weeklyAiSummary": "每週 AI 摘要",
    "settings.weeklyAiSummaryDesc": "每個星期一朝早",
    "settings.alertWhenBelow": "低於呢個日數就提醒",
    "settings.careTeamAccess": "護理團隊權限",
    "settings.addCareTeamMember": "新增護理團隊成員",
    "settings.privacySecurity": "私隱與保安",
    "settings.dataEncryption": "數據加密",
    "settings.dataEncryptionDesc": "端對端加密",
    "settings.pdpaCompliance": "符合 PDPA 規定",
    "settings.pdpaComplianceDesc": "新加坡 2012 年 PDPA",
    "settings.auditLog": "審計日誌",
    "settings.auditLogDesc": "所有存取事件都會記錄",
    "settings.switchToElderly": "切換去長者模式",
    "settings.footer": "喺新加坡用心製作",
    "ai.chatTab": "同Mei傾",
    "ai.doctorTab": "問醫生",
    "ai.quickHelp": "快速幫手",
    "ai.helpSetup": "幫我設定",
    "ai.languageVoice": "語言同語音",
    "ai.speaking": "講緊",
    "dashboard.dosesTaken": "已服用 {taken} / {total} 劑",
    "dashboard.missedDoseAlert": "漏服提醒",
    "dashboard.wasDueAt": "{name} {dose} — 應該喺 {time} 服用",
    "dashboard.remind": "提醒",
    "dashboard.daysRemainingOrderSoon": "仲剩 {days} 日 · 請盡快訂購",
    "dashboard.quickActions": "快速操作",
    "common.home": "首頁",
    "common.schedule": "時間表",
    "common.askMei": "問Mei",
    "common.patient": "病人",
    "common.settings": "設定",
    "common.today": "今日",
    "common.daily": "每日",
    "common.weekly": "每週",
    "common.viewSchedule": "睇時間表",
    "common.checkSchedule": "查看時間表",
    "common.sendReminder": "發送提醒",
    "common.leaveNote": "留言",
    "common.emergency": "緊急",
    "common.addPrescription": "新增處方",
    "common.edit": "編輯",
    "common.add": "+ 新增",
    "common.fullName": "全名",
    "common.roleExample": "角色（例如：醫生、女兒、傭工）",
    "common.removeMedication": "移除藥物",
    "common.medicalConditions": "病情",
    "common.knownAllergies": "已知過敏",
    "common.currentMedications": "目前藥物",
    "common.pastMedications": "以前藥物",
    "common.relationAge": "{relation} · {age} 歲",
    "common.bloodType": "血型 {type}",
    "common.conditionsCount": "{count} 項病情",
    "common.medicationsCount": "{count} 種藥物",
    "common.emergencyContacts": "緊急聯絡人",
    "common.addOne": "新增一個",
    "common.noConditionsRecorded": "未有記錄病情。",
    "common.noAllergiesRecorded": "未有記錄過敏。",
    "common.daysOfSupplyLeft": "仲剩 {count} 日藥量",
    "common.notDue": "未到時間",
    "common.taken": "已服用",
    "common.missed": "漏服",
    "common.upcoming": "即將到嚟",
    "common.dismiss": "關閉",
    "common.requested": "已要求",
    "common.allClear": "一切正常",
    "common.noPendingNotifications": "冇待處理嘅通知。",
    "common.callPatient": "致電病人",
    "common.orderRefill": "訂購補藥",
    "common.weeklySummary": "每週摘要",
    "common.travelMode": "旅行模式",
    "common.askMeiPlaceholder": "問Mei關於呢位病人嘅事...",
    "common.signIn": "登入",
    "common.welcomeBack": "歡迎返嚟",
    "common.signInToContinue": "登入以繼續使用 Dosewise。",
    "common.dontHaveAccount": "未有帳戶？開始使用",
    "common.getStarted": "開始使用",
    "common.alreadyHaveAccount": "我已經有帳戶",
    "common.whoAreYouUsing": "你今日係\n為邊個用 Dosewise？",
    "common.forLovedOne": "為摯愛的人",
    "common.forMyself": "為自己",
    "common.modeHint": "我哋會根據你想點樣用呢個 app\n嚟調整你嘅體驗。",
    "common.switchModesHint": "你隨時可以喺設定度切換模式。",
    "common.howSetUp": "你想點樣\n設定你嘅資料？",
    "common.setUpHint": "揀邊個容易啲都得 — 你之後隨時可以加多啲資料。",
    "common.healthHub": "用 HealthHub 登入",
    "common.healthHubComingSoon": "即將推出",
    "common.guidedSetup": "回答幾條簡單問題",
    "common.setupMinutes": "呢個只需要幾分鐘。",
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.medications": "மருந்துகள்",
    "nav.askMei": "Mei-ஐக் கேளுங்கள்",
    "nav.notifications": "அறிவிப்புகள்",
    "nav.settings": "அமைப்புகள்",
    "header.hello": "வணக்கம், {name}!",
    "home.today": "இன்று",
    "home.scheduled": "திட்டமிடப்பட்டது",
    "home.comingUp": "விரைவில்",
    "home.taken": "எடுக்கப்பட்டது",
    "home.takenAt": "{time} க்கு எடுக்கப்பட்டது",
    "home.vagueTimeNote": "{note} · சுமார் {clock}",
    "home.morning": "காலை",
    "home.afternoon": "மதியம்",
    "home.evening": "மாலை",
    "home.night": "இரவு",
    "home.iTookIt": "நான் எடுத்துவிட்டேன் ✓",
    "home.markTaken": "எடுத்ததாக குறிக்கவும்",
    "home.whatTime": "எந்த நேரத்தில் எடுத்தீர்கள்?",
    "home.justNow": "இப்போதே",
    "home.confirm": "உறுதிப்படுத்தவும்",
    "home.recorded": "பதிவு செய்யப்பட்டது! அருமை 🌟",
    "home.now": "இப்போது",
    "home.refillNeeded": "மறுபொருத்தம் விரைவில் தேவை",
    "home.noSchedule": "திட்டமிடப்பட்ட மருந்துகள் இல்லை.",
    "home.takeAsDirected": "எப்போதும் மருத்துவர் பரிந்துரைத்தபடி மருந்தை எடுத்துக்கொள்ளுங்கள்.",
    "home.timesShownIn": "நேரங்கள் {tz} இல் காட்டப்படுகின்றன",
    "home.tapToView": "பார்க்க தட்டவும்",
    "home.hide": "மறை",
    "home.scheduledFor": "{clock} க்கு திட்டமிடப்பட்டது",
    "home.willLogAs": "{time} என பதிவு செய்யப்படும்",
    "prescription.count": "{count} மருந்துகள்",
    "prescription.add": "மறுபொருத்தம் / மருந்து சேர்க்கவும்",
    "prescription.empty": "இன்னும் மருந்துகள் சேர்க்கப்படவில்லை — மேலே உள்ள “மறுபொருத்தம் / மருந்து சேர்க்கவும்” என்பதைத் தட்டவும்.",
    "prescription.supply": "எஞ்சிய இருப்பு",
    "prescription.past": "முன்பு எடுத்த மருந்துகள்",
    "prescription.disclaimer": "மருந்துகளை எப்போதும் மருத்துவர் பரிந்துரைத்தபடியே எடுத்துக்கொள்ளுங்கள். உங்கள் மருத்துவரை கலந்தாலோசிக்காமல் நிறுத்தவோ மாற்றவோ வேண்டாம்.",
    "prescription.daysLeftBadge": "{days} நாட்கள் மீதம்",
    "prescription.forPurpose": "{purpose} க்காக",
    "prescription.howToUseEyeDrops": "கண் சொட்டு மருந்தை எப்படி பயன்படுத்துவது",
    "prescription.supplyOfTotal": "{days}/30 நாட்கள்",
    "prescription.stepByStepGuide": "படிப்படியான வழிகாட்டி",
    "prescription.eyeDropsAlt": "கண் சொட்டு மருந்து செயல்விளக்கம்",
    "prescription.watchHowToUse": "பார்க்க: கண் சொட்டு மருந்தை எப்படி பயன்படுத்துவது",
    "prescription.videoGuideLength": "வீடியோ வழிகாட்டி · 2 நிமிடம்",
    "notifications.header": "உங்கள் குடும்பத்தினர் மற்றும் பராமரிப்பு குழுவின் செய்திகள்",
    "notifications.empty": "பராமரிப்பாளரிடமிருந்து இன்னும் செய்திகள் இல்லை.",
    "settings.voiceAndLanguage": "குரல் மற்றும் மொழி",
    "settings.readAloud": "குரலில் படிக்கவும்",
    "settings.readAloudDesc": "Mei தனது பதில்களை சத்தமாக படிக்கும்",
    "settings.language": "மொழி",
    "settings.languageDesc": "Mei இன் பதில்கள் உட்பட, செயலி முழுவதும் பயன்படுத்தப்படுகிறது",
    "settings.yourProfile": "உங்கள் சுயவிவரம்",
    "settings.age": "வயது",
    "settings.dob": "பிறந்த தேதி",
    "settings.gender": "பாலினம்",
    "settings.weightKg": "எடை (kg)",
    "settings.heightCm": "உயரம் (cm)",
    "settings.medicalConditions": "மருத்துவ நிலைமைகள்",
    "settings.generalAllergies": "பொது ஒவ்வாமைகள்",
    "settings.medicationAllergies": "மருந்து ஒவ்வாமைகள்",
    "settings.mealsSleep": "உணவு & தூக்கம்",
    "settings.saveChanges": "மாற்றங்களை சேமிக்கவும்",
    "settings.saving": "சேமிக்கிறது…",
    "settings.saved": "சேமிக்கப்பட்டது!",
    "settings.accessibility": "அணுகல்தன்மை",
    "settings.textSize": "எழுத்து அளவு",
    "settings.textSizeDesc": "எழுத்தை சிறியதாகவோ பெரியதாகவோ மாற்ற இழுக்கவும்",
    "settings.highContrast": "அதிக மாறுபாடு",
    "settings.highContrastDesc": "படிப்பதற்கு எளிதாக இருக்க தடிமனான வண்ணங்கள் மற்றும் வலுவான கோடுகள்",
    "settings.colourBlindMode": "நிற குருட்டு பயன்முறை",
    "settings.colourBlindDesc": "ஒவ்வொரு மருந்தையும் அடையாளம் காண மாத்திரையின் வடிவம், குறியீடு, உரையைப் பயன்படுத்துகிறது — நிறத்தை அல்ல",
    "settings.medicationDescriptions": "உங்கள் மருந்து விவரங்கள்",
    "settings.reminders": "நினைவூட்டல்கள்",
    "settings.medicationReminders": "மருந்து நினைவூட்டல்கள்",
    "settings.medicationRemindersDesc": "மருந்து எடுக்க வேண்டிய நேரத்தில் எச்சரிக்கவும்",
    "settings.emergencyContact": "அவசர தொடர்பு",
    "settings.switchToCaregiver": "பராமரிப்பாளர் பயன்முறைக்கு மாறவும்",
    "settings.signOut": "வெளியேறு",
    "settings.account": "கணக்கு",
    "settings.editProfile": "சுயவிவரத்தைத் திருத்து",
    "settings.missedDoseAlerts": "தவறவிட்ட மருந்து எச்சரிக்கைகள்",
    "settings.missedDoseAlertsDesc": "உடனடி புஷ் அறிவிப்பு",
    "settings.refillReminders": "மறுநிரப்பு நினைவூட்டல்கள்",
    "settings.refillRemindersDesc": "இருப்பு {days} நாட்களுக்குக் கீழே குறையும்போது எச்சரிக்கவும்",
    "settings.weeklyAiSummary": "வாராந்திர AI சுருக்கம்",
    "settings.weeklyAiSummaryDesc": "ஒவ்வொரு திங்கள் காலை",
    "settings.alertWhenBelow": "இதற்குக் கீழே எச்சரிக்கவும்",
    "settings.careTeamAccess": "பராமரிப்பு குழு அணுகல்",
    "settings.addCareTeamMember": "பராமரிப்பு குழு உறுப்பினரைச் சேர்க்கவும்",
    "settings.privacySecurity": "தனியுரிமை & பாதுகாப்பு",
    "settings.dataEncryption": "தரவு குறியாக்கம்",
    "settings.dataEncryptionDesc": "எண்ட்-டு-எண்ட் குறியாக்கம்",
    "settings.pdpaCompliance": "PDPA இணக்கம்",
    "settings.pdpaComplianceDesc": "சிங்கப்பூர் PDPA 2012",
    "settings.auditLog": "தணிக்கை பதிவு",
    "settings.auditLogDesc": "அனைத்து அணுகல் நிகழ்வுகளும் பதிவு செய்யப்படுகின்றன",
    "settings.switchToElderly": "முதியோர் பயன்முறைக்கு மாறவும்",
    "settings.footer": "சிங்கப்பூரில் அக்கறையுடன் உருவாக்கப்பட்டது",
    "ai.chatTab": "Mei-யுடன் அரட்டையடிக்கவும்",
    "ai.doctorTab": "டாக்டரிடம் கேளுங்கள்",
    "ai.quickHelp": "விரைவு உதவி",
    "ai.helpSetup": "எனக்கு அமைக்க உதவுங்கள்",
    "ai.languageVoice": "மொழி மற்றும் குரல்",
    "ai.speaking": "பேசுகிறது",
    "dashboard.dosesTaken": "{total} இல் {taken} அளவுகள் எடுக்கப்பட்டன",
    "dashboard.missedDoseAlert": "தவறவிட்ட மருந்து எச்சரிக்கை",
    "dashboard.wasDueAt": "{name} {dose} — {time} க்கு எடுக்க வேண்டியிருந்தது",
    "dashboard.remind": "நினைவூட்டு",
    "dashboard.daysRemainingOrderSoon": "{days} நாட்கள் மீதமுள்ளன · விரைவில் ஆர்டர் செய்யவும்",
    "dashboard.quickActions": "விரைவு செயல்கள்",
    "common.home": "முகப்பு",
    "common.schedule": "அட்டவணை",
    "common.askMei": "Mei-ஐக் கேளுங்கள்",
    "common.patient": "நோயாளி",
    "common.settings": "அமைப்புகள்",
    "common.today": "இன்று",
    "common.daily": "தினசரி",
    "common.weekly": "வாராந்திரம்",
    "common.viewSchedule": "அட்டவணையைப் பார்க்கவும்",
    "common.checkSchedule": "அட்டவணையைச் சரிபார்க்கவும்",
    "common.sendReminder": "நினைவூட்டல் அனுப்பவும்",
    "common.leaveNote": "குறிப்பு விடவும்",
    "common.emergency": "அவசரம்",
    "common.addPrescription": "மருந்துச்சீட்டு சேர்க்கவும்",
    "common.edit": "திருத்து",
    "common.add": "+ சேர்",
    "common.fullName": "முழுப் பெயர்",
    "common.roleExample": "பங்கு (எ.கா. மருத்துவர், மகள், உதவியாளர்)",
    "common.removeMedication": "மருந்தை அகற்று",
    "common.medicalConditions": "மருத்துவ நிலைமைகள்",
    "common.knownAllergies": "அறியப்பட்ட ஒவ்வாமைகள்",
    "common.currentMedications": "தற்போதைய மருந்துகள்",
    "common.pastMedications": "முந்தைய மருந்துகள்",
    "common.relationAge": "{relation} · வயது {age}",
    "common.bloodType": "இரத்தப் பிரிவு {type}",
    "common.conditionsCount": "{count} நிலைமைகள்",
    "common.medicationsCount": "{count} மருந்துகள்",
    "common.emergencyContacts": "அவசரத் தொடர்புகள்",
    "common.addOne": "ஒன்று சேர்க்கவும்",
    "common.noConditionsRecorded": "நிலைமைகள் எதுவும் பதிவு செய்யப்படவில்லை.",
    "common.noAllergiesRecorded": "ஒவ்வாமைகள் எதுவும் பதிவு செய்யப்படவில்லை.",
    "common.daysOfSupplyLeft": "{count} நாட்கள் இருப்பு மீதம்",
    "common.notDue": "நேரம் ஆகவில்லை",
    "common.taken": "எடுக்கப்பட்டது",
    "common.missed": "தவறவிட்டது",
    "common.upcoming": "வரவிருக்கிறது",
    "common.dismiss": "நிராகரி",
    "common.requested": "கோரப்பட்டது",
    "common.allClear": "அனைத்தும் சரி",
    "common.noPendingNotifications": "நிலுவையில் அறிவிப்புகள் இல்லை.",
    "common.callPatient": "நோயாளியை அழைக்கவும்",
    "common.orderRefill": "மறுநிரப்பு ஆர்டர் செய்யவும்",
    "common.weeklySummary": "வாராந்திர சுருக்கம்",
    "common.travelMode": "பயண பயன்முறை",
    "common.askMeiPlaceholder": "இந்த நோயாளியைப் பற்றி Mei-யிடம் கேளுங்கள்...",
    "common.signIn": "உள்நுழைக",
    "common.welcomeBack": "மீண்டும் வரவேற்கிறோம்",
    "common.signInToContinue": "Dosewise தொடர உள்நுழையவும்.",
    "common.dontHaveAccount": "கணக்கு இல்லையா? தொடங்குங்கள்",
    "common.getStarted": "தொடங்குங்கள்",
    "common.alreadyHaveAccount": "என்னிடம் ஏற்கனவே கணக்கு உள்ளது",
    "common.whoAreYouUsing": "இன்று நீங்கள் யாருக்காக\nDosewise பயன்படுத்துகிறீர்கள்?",
    "common.forLovedOne": "அன்பானவருக்காக",
    "common.forMyself": "எனக்காக",
    "common.modeHint": "நீங்கள் செயலியை எப்படிப் பயன்படுத்த விரும்புகிறீர்கள்\nஎன்பதன் அடிப்படையில் உங்கள் அனுபவத்தை வடிவமைப்போம்.",
    "common.switchModesHint": "அமைப்புகளில் எப்போது வேண்டுமானாலும் பயன்முறையை மாற்றலாம்.",
    "common.howSetUp": "உங்கள் சுயவிவரத்தை எப்படி\nஅமைக்க விரும்புகிறீர்கள்?",
    "common.setUpHint": "எது எளிதாக இருக்கிறதோ அதைத் தேர்ந்தெடுங்கள் — பின்னர் மேலும் விவரங்களைச் சேர்க்கலாம்.",
    "common.healthHub": "HealthHub மூலம் உள்நுழையவும்",
    "common.healthHubComingSoon": "விரைவில் வருகிறது",
    "common.guidedSetup": "சில எளிய கேள்விகளுக்குப் பதிலளிக்கவும்",
    "common.setupMinutes": "இதற்கு சில நிமிடங்கள் மட்டுமே ஆகும்.",
  },
  ms: {
    "nav.home": "Laman Utama",
    "nav.medications": "Ubat",
    "nav.askMei": "Tanya Mei",
    "nav.notifications": "Pemberitahuan",
    "nav.settings": "Tetapan",
    "header.hello": "Halo, {name}!",
    "home.today": "Hari Ini",
    "home.scheduled": "Dijadualkan",
    "home.comingUp": "Akan Datang",
    "home.taken": "diambil",
    "home.takenAt": "Diambil pada {time}",
    "home.vagueTimeNote": "{note} · sekitar {clock}",
    "home.morning": "Pagi",
    "home.afternoon": "Tengah Hari",
    "home.evening": "Petang",
    "home.night": "Malam",
    "home.iTookIt": "Saya Sudah Ambil ✓",
    "home.markTaken": "Tandakan sebagai diambil",
    "home.whatTime": "Bila anda ambil ubat itu?",
    "home.justNow": "Baru sahaja",
    "home.confirm": "Sahkan",
    "home.recorded": "Direkodkan! Hebat 🌟",
    "home.now": "Sekarang",
    "home.refillNeeded": "Ubat perlu diisi semula tidak lama lagi",
    "home.noSchedule": "Tiada ubat yang dijadualkan.",
    "home.takeAsDirected": "Sentiasa ambil ubat mengikut arahan doktor anda.",
    "home.timesShownIn": "Masa dipaparkan dalam {tz}",
    "home.tapToView": "Ketik untuk lihat",
    "home.hide": "Sembunyi",
    "home.scheduledFor": "Dijadualkan pada {clock}",
    "home.willLogAs": "Akan direkodkan sebagai {time}",
    "prescription.count": "{count} ubat",
    "prescription.add": "Tambah isi semula / preskripsi",
    "prescription.empty": "Tiada ubat lagi — ketik “Tambah isi semula / preskripsi” di atas untuk bermula.",
    "prescription.supply": "Baki stok",
    "prescription.past": "Ubat yang lepas",
    "prescription.disclaimer": "Sentiasa ambil ubat mengikut preskripsi doktor. Jangan berhenti atau tukar dos tanpa berunding dengan doktor.",
    "prescription.daysLeftBadge": "{days}h lagi",
    "prescription.forPurpose": "Untuk {purpose}",
    "prescription.howToUseEyeDrops": "Cara menggunakan titisan mata",
    "prescription.supplyOfTotal": "{days}/30 hari",
    "prescription.stepByStepGuide": "Panduan langkah demi langkah",
    "prescription.eyeDropsAlt": "Demonstrasi titisan mata",
    "prescription.watchHowToUse": "Tonton: Cara menggunakan titisan mata",
    "prescription.videoGuideLength": "Panduan video · 2 minit",
    "notifications.header": "Mesej daripada keluarga dan pasukan penjagaan",
    "notifications.empty": "Tiada mesej daripada penjaga lagi.",
    "settings.voiceAndLanguage": "Suara & Bahasa",
    "settings.readAloud": "Baca dengan kuat",
    "settings.readAloudDesc": "Mei membacakan balasannya dengan kuat",
    "settings.language": "Bahasa",
    "settings.languageDesc": "Digunakan di seluruh aplikasi, termasuk balasan Mei",
    "settings.yourProfile": "Profil Anda",
    "settings.age": "Umur",
    "settings.dob": "Tarikh lahir",
    "settings.gender": "Jantina",
    "settings.weightKg": "Berat (kg)",
    "settings.heightCm": "Tinggi (cm)",
    "settings.medicalConditions": "Keadaan perubatan",
    "settings.generalAllergies": "Alahan am",
    "settings.medicationAllergies": "Alahan ubat",
    "settings.mealsSleep": "Waktu makan & tidur",
    "settings.saveChanges": "Simpan perubahan",
    "settings.saving": "Menyimpan…",
    "settings.saved": "Disimpan!",
    "settings.accessibility": "Kebolehcapaian",
    "settings.textSize": "Saiz Teks",
    "settings.textSizeDesc": "Seret untuk kecilkan atau besarkan teks",
    "settings.highContrast": "Kontras Tinggi",
    "settings.highContrastDesc": "Warna lebih terang dan garis besar lebih kuat untuk mudah dibaca",
    "settings.colourBlindMode": "Mod Buta Warna",
    "settings.colourBlindDesc": "Menggunakan bentuk pil, tanda, dan teks — bukan warna — untuk mengenal pasti setiap ubat",
    "settings.medicationDescriptions": "Penerangan ubat anda",
    "settings.reminders": "Peringatan",
    "settings.medicationReminders": "Peringatan Ubat",
    "settings.medicationRemindersDesc": "Beri amaran apabila tiba masa mengambil ubat",
    "settings.emergencyContact": "Kenalan Kecemasan",
    "settings.switchToCaregiver": "Tukar ke Mod Penjaga",
    "settings.signOut": "Log keluar",
    "settings.account": "Akaun",
    "settings.editProfile": "Sunting profil",
    "settings.missedDoseAlerts": "Amaran ubat terlepas",
    "settings.missedDoseAlertsDesc": "Pemberitahuan tolak segera",
    "settings.refillReminders": "Peringatan isi semula",
    "settings.refillRemindersDesc": "Beri amaran apabila stok kurang daripada {days} hari",
    "settings.weeklyAiSummary": "Ringkasan AI mingguan",
    "settings.weeklyAiSummaryDesc": "Setiap pagi Isnin",
    "settings.alertWhenBelow": "Beri amaran apabila kurang daripada",
    "settings.careTeamAccess": "Akses Pasukan Penjagaan",
    "settings.addCareTeamMember": "Tambah ahli pasukan penjagaan",
    "settings.privacySecurity": "Privasi & Keselamatan",
    "settings.dataEncryption": "Penyulitan data",
    "settings.dataEncryptionDesc": "Disulitkan hujung ke hujung",
    "settings.pdpaCompliance": "Pematuhan PDPA",
    "settings.pdpaComplianceDesc": "PDPA Singapura 2012",
    "settings.auditLog": "Log audit",
    "settings.auditLogDesc": "Semua peristiwa akses direkodkan",
    "settings.switchToElderly": "Tukar ke Mod Warga Emas",
    "settings.footer": "Dibuat dengan teliti di Singapura",
    "ai.chatTab": "Bual dengan Mei",
    "ai.doctorTab": "Tanya Doktor",
    "ai.quickHelp": "Bantuan cepat",
    "ai.helpSetup": "Bantu saya sediakan",
    "ai.languageVoice": "Bahasa & suara",
    "ai.speaking": "Bercakap",
    "dashboard.dosesTaken": "{taken} daripada {total} dos diambil",
    "dashboard.missedDoseAlert": "Amaran ubat terlepas",
    "dashboard.wasDueAt": "{name} {dose} — sepatutnya diambil pada {time}",
    "dashboard.remind": "Ingatkan",
    "dashboard.daysRemainingOrderSoon": "{days} hari lagi · Tempah tidak lama lagi",
    "dashboard.quickActions": "Tindakan Pantas",
    "common.home": "Laman Utama",
    "common.schedule": "Jadual",
    "common.askMei": "Tanya Mei",
    "common.patient": "Pesakit",
    "common.settings": "Tetapan",
    "common.today": "Hari Ini",
    "common.daily": "Harian",
    "common.weekly": "Mingguan",
    "common.viewSchedule": "Lihat Jadual",
    "common.checkSchedule": "Semak Jadual",
    "common.sendReminder": "Hantar Peringatan",
    "common.leaveNote": "Tinggalkan Nota",
    "common.emergency": "Kecemasan",
    "common.addPrescription": "Tambah preskripsi",
    "common.edit": "Sunting",
    "common.add": "+ Tambah",
    "common.fullName": "Nama penuh",
    "common.roleExample": "Peranan (cth. Doktor, Anak perempuan, Pembantu)",
    "common.removeMedication": "Buang ubat",
    "common.medicalConditions": "Keadaan Perubatan",
    "common.knownAllergies": "Alahan Diketahui",
    "common.currentMedications": "Ubat Semasa",
    "common.pastMedications": "Ubat Lepas",
    "common.relationAge": "{relation} · Umur {age}",
    "common.bloodType": "Jenis Darah {type}",
    "common.conditionsCount": "{count} Keadaan",
    "common.medicationsCount": "{count} Ubat",
    "common.emergencyContacts": "Kenalan Kecemasan",
    "common.addOne": "Tambah satu",
    "common.noConditionsRecorded": "Tiada keadaan direkodkan.",
    "common.noAllergiesRecorded": "Tiada alahan direkodkan.",
    "common.daysOfSupplyLeft": "{count} hari bekalan lagi",
    "common.notDue": "Belum tiba masa",
    "common.taken": "Diambil",
    "common.missed": "Terlepas",
    "common.upcoming": "Akan Datang",
    "common.dismiss": "Tolak",
    "common.requested": "Diminta",
    "common.allClear": "Semua selesai",
    "common.noPendingNotifications": "Tiada pemberitahuan tertunda.",
    "common.callPatient": "Hubungi Pesakit",
    "common.orderRefill": "Tempah Isi Semula",
    "common.weeklySummary": "Ringkasan Mingguan",
    "common.travelMode": "Mod Perjalanan",
    "common.askMeiPlaceholder": "Tanya Mei tentang pesakit ini...",
    "common.signIn": "Log masuk",
    "common.welcomeBack": "Selamat kembali",
    "common.signInToContinue": "Log masuk untuk teruskan ke Dosewise.",
    "common.dontHaveAccount": "Tiada akaun? Mulakan",
    "common.getStarted": "Mulakan",
    "common.alreadyHaveAccount": "Saya sudah ada akaun",
    "common.whoAreYouUsing": "Untuk siapa anda menggunakan\nDosewise hari ini?",
    "common.forLovedOne": "Untuk Orang Tersayang",
    "common.forMyself": "Untuk Diri Sendiri",
    "common.modeHint": "Kami akan sesuaikan pengalaman anda\nberdasarkan cara anda mahu menggunakan aplikasi.",
    "common.switchModesHint": "Anda boleh tukar mod bila-bila masa dalam Tetapan.",
    "common.howSetUp": "Bagaimana anda mahu\nmenyediakan profil anda?",
    "common.setUpHint": "Pilih mana-mana yang lebih mudah — anda sentiasa boleh tambah butiran kemudian.",
    "common.healthHub": "Log masuk dengan HealthHub",
    "common.healthHubComingSoon": "Akan datang",
    "common.guidedSetup": "Jawab beberapa soalan mudah",
    "common.setupMinutes": "Ini hanya mengambil masa beberapa minit.",
  },
};

export function t(language: AppLanguage, key: string, params?: Record<string, string | number>) {
  const value = TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  return Object.entries(params ?? {}).reduce((acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)), value);
}

export function getLanguageLabel(language: AppLanguage) {
  return LANGUAGE_OPTIONS.find(option => option.id === language)?.label ?? LANGUAGE_OPTIONS[0].label;
}

// The natural-language name sent to Hermes as `reply_language` ("reply in {x}") —
// undefined for English keeps the agent's default behaviour.
const REPLY_LANGUAGE: Record<AppLanguage, string | undefined> = {
  en: undefined,
  zh: "Mandarin Chinese",
  hokkien: "Hokkien",
  yue: "Cantonese",
  ta: "Tamil",
  ms: "Malay",
};

export function replyLanguageFor(language: AppLanguage): string | undefined {
  return REPLY_LANGUAGE[language];
}

// Browser SpeechRecognition / speechSynthesis language tags.
const SPEECH_LANG: Record<AppLanguage, string> = {
  en: "en-SG",
  zh: "zh-CN",
  hokkien: "zh-CN",
  yue: "zh-HK",
  ta: "ta-IN",
  ms: "ms-MY",
};

export function speechLangFor(language: AppLanguage): string {
  return SPEECH_LANG[language];
}

// Optional curated, human-reviewed translations of a medication's simple
// instruction, keyed by language → medication name. Medication dosing text is
// safety-sensitive, so we deliberately do NOT machine-translate it: when no
// curated string exists we fall back to the (curated, English) `fallback` the
// caller passes in rather than risk a wrong auto-translation of a dose. Extend
// this table with reviewed translations to localise med directions per language.
type MedTextStyle = "simple";
const MED_TEXT_I18N: Partial<Record<AppLanguage, Record<string, string>>> = {};

export function localizeMedText(
  language: AppLanguage,
  medName: string,
  _style: MedTextStyle,
  fallback: string,
): string {
  return MED_TEXT_I18N[language]?.[medName] ?? fallback;
}
