export type AppLanguage = "en" | "zh" | "hokkien" | "yue" | "ta" | "ms";

export const LANGUAGE_OPTIONS: { id: AppLanguage; label: string }[] = [
  { id: "en", label: "English" },
  { id: "zh", label: "华语 (Mandarin)" },
  { id: "hokkien", label: "闽南话 (Hokkien)" },
  { id: "yue", label: "粤语 (Cantonese)" },
  { id: "ta", label: "தமிழ் (Tamil)" },
  { id: "ms", label: "Melayu" },
];

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.medications": "Medications",
    "nav.askMei": "Ask Mei",
    "nav.notifications": "Notifications",
    "nav.settings": "Settings",
    "header.hello": "Hello, {name}!",
    "home.today": "Today",
    "home.scheduled": "Scheduled",
    "home.comingUp": "Coming up",
    "home.taken": "taken",
    "home.iTookIt": "I Took It ✓",
    "home.markTaken": "Mark as taken",
    "home.whatTime": "What time did you take it?",
    "home.justNow": "Just now",
    "home.confirm": "Confirm",
    "home.recorded": "Recorded! Well done 🌟",
    "home.now": "Now",
    "home.refillNeeded": "Refill needed soon",
    "home.noSchedule": "No medications scheduled.",
    "prescription.count": "{count} medications",
    "prescription.add": "Add refill / prescription",
    "prescription.empty": "No medicines added yet — tap \"Add refill / prescription\" above to get started.",
    "prescription.supply": "Supply remaining",
    "prescription.past": "Past medications",
    "prescription.disclaimer": "Always take medications exactly as prescribed. Never stop or change your dose without checking with your doctor first.",
    "notifications.header": "Messages from your family and care team",
    "notifications.empty": "No messages yet from your caregiver.",
    "settings.voiceAndLanguage": "Voice & Language",
    "settings.readAloud": "Read Aloud",
    "settings.readAloudDesc": "Mei reads her replies out loud",
    "settings.language": "Language",
    "settings.languageDesc": "Mei responds in this language",
    "settings.yourProfile": "Your Profile",
    "settings.age": "Age",
    "settings.gender": "Gender",
    "settings.weightKg": "Weight (kg)",
    "settings.heightCm": "Height (cm)",
    "settings.medicalConditions": "Medical conditions",
    "settings.generalAllergies": "General allergies",
    "settings.medicationAllergies": "Medication allergies",
    "settings.mealsSleep": "Meals & sleep",
    "settings.saveChanges": "Save changes",
    "settings.saving": "Saving…",
    "settings.saved": "Saved!",
    "settings.accessibility": "Accessibility",
    "settings.textSize": "Text Size",
    "settings.textSizeDesc": "Drag to make text smaller or larger",
    "settings.highContrast": "High Contrast",
    "settings.highContrastDesc": "Bolder colours and stronger outlines for easier reading",
    "settings.colourBlindMode": "Colour Blind Mode",
    "settings.colourBlindDesc": "Uses pill shape, markings, and text — not colour — to identify each medication",
    "settings.medicationDescriptions": "Your medication descriptions",
    "settings.reminders": "Reminders",
    "settings.medicationReminders": "Medication Reminders",
    "settings.medicationRemindersDesc": "Alert when it's time to take medication",
    "settings.emergencyContact": "Emergency Contact",
    "settings.switchToCaregiver": "Switch to Caregiver Mode",
    "settings.signOut": "Sign out",
    "ai.chatTab": "Chat with Mei",
    "ai.doctorTab": "Ask Doctor",
    "ai.quickHelp": "Quick help",
    "ai.helpSetup": "Help me set up",
    "ai.languageVoice": "Language & voice",
    "ai.speaking": "Speaking",
    "common.home": "Home",
    "common.schedule": "Schedule",
    "common.askMei": "Ask Mei",
    "common.patient": "Patient",
    "common.settings": "Settings",
    "common.today": "Today",
    "common.daily": "Daily",
    "common.weekly": "Weekly",
    "common.viewSchedule": "View Schedule",
    "common.checkSchedule": "Check Schedule",
    "common.sendReminder": "Send Reminder",
    "common.leaveNote": "Leave Note",
    "common.emergency": "Emergency",
    "common.addPrescription": "Add prescription",
    "common.edit": "Edit",
    "common.add": "+ Add",
    "common.removeMedication": "Remove medication",
    "common.medicalConditions": "Medical Conditions",
    "common.knownAllergies": "Known Allergies",
    "common.currentMedications": "Current Medications",
    "common.pastMedications": "Past Medications",
    "common.emergencyContacts": "Emergency Contacts",
    "common.addOne": "Add one",
    "common.noConditionsRecorded": "No conditions recorded.",
    "common.noAllergiesRecorded": "No allergies recorded.",
    "common.daysOfSupplyLeft": "{count} days of supply left",
    "common.notDue": "Not due",
    "common.taken": "Taken",
    "common.missed": "Missed",
    "common.upcoming": "Upcoming",
    "common.dismiss": "Dismiss",
    "common.allClear": "All clear",
    "common.noPendingNotifications": "No pending notifications.",
    "common.callPatient": "Call Patient",
    "common.orderRefill": "Order Refill",
    "common.weeklySummary": "Weekly Summary",
    "common.travelMode": "Travel Mode",
    "common.askMeiPlaceholder": "Ask Mei about this patient...",
    "common.signIn": "Sign in",
    "common.welcomeBack": "Welcome back",
    "common.signInToContinue": "Sign in to continue to Dosewise.",
    "common.dontHaveAccount": "Don't have an account? Get started",
    "common.getStarted": "Get started",
    "common.alreadyHaveAccount": "I already have an account",
    "common.whoAreYouUsing": "Who are you using\nDosewise for today?",
    "common.forLovedOne": "For a Loved One",
    "common.forMyself": "For Myself",
    "common.modeHint": "We'll tailor your experience based\non how you'd like to use the app.",
    "common.switchModesHint": "You can switch modes anytime in Settings.",
    "common.howSetUp": "How would you like\nto set up your profile?",
    "common.setUpHint": "Pick whichever feels easier — you can always add more details later.",
    "common.healthHub": "Sign in with HealthHub",
    "common.healthHubComingSoon": "Coming soon",
    "common.guidedSetup": "Answer a few simple questions",
    "common.setupMinutes": "This should only take a few minutes.",
  },
  zh: {
    "nav.home": "首页",
    "nav.medications": "药物",
    "nav.askMei": "问Mei",
    "nav.notifications": "通知",
    "nav.settings": "设置",
    "header.hello": "你好，{name}！",
    "home.today": "今天",
    "home.scheduled": "已安排",
    "home.comingUp": "即将到来",
    "home.taken": "已服用",
    "home.iTookIt": "我已经服用了 ✓",
    "home.markTaken": "标记为已服用",
    "home.whatTime": "你是什么时间服用的？",
    "home.justNow": "刚刚",
    "home.confirm": "确认",
    "home.recorded": "已记录！做得很好 🌟",
    "home.now": "现在",
    "home.refillNeeded": "药量快用完",
    "home.noSchedule": "没有安排的药物。",
    "prescription.count": "{count} 种药物",
    "prescription.add": "添加续药 / 处方",
    "prescription.empty": "还没有药物 — 点击上方的“添加续药 / 处方”开始。",
    "prescription.supply": "剩余供应",
    "prescription.past": "过去服用过的药物",
    "prescription.disclaimer": "请严格按照医生开的药方服药。不要自行停药或更改剂量。",
    "notifications.header": "来自家人和护理团队的消息",
    "notifications.empty": "还没有护理人员发来的消息。",
    "settings.voiceAndLanguage": "语音与语言",
    "settings.readAloud": "朗读回复",
    "settings.readAloudDesc": "Mei 会把回复读出来",
    "settings.language": "语言",
    "settings.languageDesc": "Mei 会用这种语言回复",
    "settings.yourProfile": "您的资料",
    "settings.age": "年龄",
    "settings.gender": "性别",
    "settings.weightKg": "体重 (kg)",
    "settings.heightCm": "身高 (cm)",
    "settings.medicalConditions": "医疗状况",
    "settings.generalAllergies": "一般过敏",
    "settings.medicationAllergies": "药物过敏",
    "settings.mealsSleep": "饮食与睡眠",
    "settings.saveChanges": "保存更改",
    "settings.saving": "正在保存…",
    "settings.saved": "已保存！",
    "settings.accessibility": "无障碍",
    "settings.textSize": "文字大小",
    "settings.textSizeDesc": "拖动以缩小或放大文字",
    "settings.highContrast": "高对比度",
    "settings.highContrastDesc": "更大胆的颜色和更清晰的轮廓，方便阅读",
    "settings.colourBlindMode": "色盲模式",
    "settings.colourBlindDesc": "使用药丸形状、标记和文字，而不是颜色来识别每种药物",
    "settings.medicationDescriptions": "您的药物说明",
    "settings.reminders": "提醒",
    "settings.medicationReminders": "药物提醒",
    "settings.medicationRemindersDesc": "到药物服用时间时提醒",
    "settings.emergencyContact": "紧急联系人",
    "settings.switchToCaregiver": "切换到照护者模式",
    "settings.signOut": "退出登录",
    "ai.chatTab": "与Mei聊天",
    "ai.doctorTab": "问医生",
    "ai.quickHelp": "快速帮助",
    "ai.helpSetup": "帮我设置",
    "ai.languageVoice": "语言与语音",
    "ai.speaking": "正在说",
    "common.home": "首页",
    "common.schedule": "日程",
    "common.askMei": "问Mei",
    "common.patient": "患者",
    "common.settings": "设置",
    "common.today": "今天",
    "common.daily": "每日",
    "common.weekly": "每周",
    "common.viewSchedule": "查看日程",
    "common.checkSchedule": "查看日程",
    "common.sendReminder": "发送提醒",
    "common.leaveNote": "留言",
    "common.emergency": "紧急情况",
    "common.addPrescription": "添加处方",
    "common.edit": "编辑",
    "common.add": "+ 添加",
    "common.removeMedication": "移除药物",
    "common.medicalConditions": "医疗状况",
    "common.knownAllergies": "已知过敏",
    "common.currentMedications": "当前药物",
    "common.pastMedications": "既往药物",
    "common.emergencyContacts": "紧急联系人",
    "common.addOne": "添加一个",
    "common.noConditionsRecorded": "尚未记录病情。",
    "common.noAllergiesRecorded": "尚未记录过敏。",
    "common.daysOfSupplyLeft": "还剩 {count} 天补给",
    "common.notDue": "不在本期",
    "common.taken": "已服用",
    "common.missed": "漏服",
    "common.upcoming": "即将到来",
    "common.dismiss": "关闭",
    "common.allClear": "一切正常",
    "common.noPendingNotifications": "没有待处理通知。",
    "common.callPatient": "联系患者",
    "common.orderRefill": "补药",
    "common.weeklySummary": "每周总结",
    "common.travelMode": "旅行模式",
    "common.askMeiPlaceholder": "向Mei询问关于这个患者的信息...",
    "common.signIn": "登录",
    "common.welcomeBack": "欢迎回来",
    "common.signInToContinue": "登录以继续使用 Dosewise。",
    "common.dontHaveAccount": "还没有账号？开始使用",
    "common.getStarted": "开始使用",
    "common.alreadyHaveAccount": "我已经有账号",
    "common.whoAreYouUsing": "你今天是\n为谁使用 Dosewise？",
    "common.forLovedOne": "为亲友使用",
    "common.forMyself": "为自己使用",
    "common.modeHint": "我们会根据你希望如何使用应用来定制体验。",
    "common.switchModesHint": "你可以随时在设置中切换模式。",
    "common.howSetUp": "你想如何\n设置你的资料？",
    "common.setUpHint": "选择任何一种方式都可以，之后也可以补充更多信息。",
    "common.healthHub": "使用 HealthHub 登录",
    "common.healthHubComingSoon": "即将推出",
    "common.guidedSetup": "回答几个简单的问题",
    "common.setupMinutes": "这只需要几分钟。",
  },
  hokkien: {
    "nav.home": "厝內",
    "nav.medications": "藥",
    "nav.askMei": "問Mei",
    "nav.notifications": "通知",
    "nav.settings": "設定",
    "header.hello": "你好，{name}！",
    "home.today": "今仔日",
    "home.scheduled": "已排好",
    "home.comingUp": "緊欲來",
    "home.taken": "已食",
    "home.iTookIt": "我已經食了 ✓",
    "home.markTaken": "標做已食",
    "home.whatTime": "你是啥時食的？",
    "home.justNow": "才無外久",
    "home.confirm": "確認",
    "home.recorded": "已記好！真好 🌟",
    "home.now": "現在",
    "home.refillNeeded": "藥差不多無矣",
    "home.noSchedule": "無安排的藥。",
    "prescription.count": "{count} 種藥",
    "prescription.add": "加續藥 / 處方",
    "prescription.empty": "猶未有藥 — 請拍上方「加續藥 / 處方」開始。",
    "prescription.supply": "剩餘藥量",
    "prescription.past": "以前食過的藥",
    "prescription.disclaimer": "請照醫生囑咐食藥。莫好家己停藥或改藥量。",
    "notifications.header": "家人佮照顧團隊的訊息",
    "notifications.empty": "猶未有照顧者送來的訊息。",
    "settings.voiceAndLanguage": "語音佮話語",
    "settings.readAloud": "讀出來",
    "settings.readAloudDesc": "Mei 會唸出伊的回覆",
    "settings.language": "話語",
    "settings.languageDesc": "Mei 會用這種話語回答",
    "ai.chatTab": "跟Mei講",
    "ai.doctorTab": "問醫生",
    "ai.quickHelp": "緊急幫助",
    "ai.helpSetup": "幫我設定",
    "ai.languageVoice": "話語佮語音",
    "ai.speaking": "咧講",
    "common.home": "厝內",
    "common.schedule": "排程",
    "common.askMei": "問Mei",
    "common.patient": "病人",
    "common.settings": "設定",
    "common.today": "今仔日",
    "common.daily": "逐日",
    "common.weekly": "逐禮拜",
    "common.viewSchedule": "看排程",
    "common.checkSchedule": "看排程",
    "common.sendReminder": "送提醒",
    "common.leaveNote": "留話",
    "common.emergency": "緊急",
    "common.addPrescription": "加處方",
    "common.edit": "改",
    "common.add": "+ 加",
    "common.removeMedication": "除去藥",
    "common.medicalConditions": "病情",
    "common.knownAllergies": "知影的過敏",
    "common.currentMedications": "現此時的藥",
    "common.pastMedications": "以前的藥",
    "common.emergencyContacts": "緊急聯絡人",
    "common.addOne": "加一項",
    "common.noConditionsRecorded": "猶未記錄病情。",
    "common.noAllergiesRecorded": "猶未記錄過敏。",
    "common.daysOfSupplyLeft": "猶剩 {count} 工藥",
    "common.notDue": "這陣無著",
    "common.taken": "已經食矣",
    "common.missed": "漏食",
    "common.upcoming": "緊欲來",
    "common.dismiss": "收掉",
    "common.allClear": "攏無事",
    "common.noPendingNotifications": "無未處理的通知。",
    "common.callPatient": "打給病人",
    "common.orderRefill": "叫續藥",
    "common.weeklySummary": "逐禮拜總結",
    "common.travelMode": "旅行模式",
    "common.askMeiPlaceholder": "問Mei有關這個病人的事情...",
    "common.signIn": "登入",
    "common.welcomeBack": "歡迎返來",
    "common.signInToContinue": "登入來續用 Dosewise。",
    "common.dontHaveAccount": "猶未有帳號？開始用",
    "common.getStarted": "開始用",
    "common.alreadyHaveAccount": "我本來就有帳號",
    "common.whoAreYouUsing": "你今仔日是\n為啥人用 Dosewise？",
    "common.forLovedOne": "為親情的人",
    "common.forMyself": "為家己",
    "common.modeHint": "阮會照你想按怎用這个 app 來調整體驗。",
    "common.switchModesHint": "你隨時會使佇設定內切換模式。",
    "common.howSetUp": "你想按怎\n設定你的資料？",
    "common.setUpHint": "揀一種就好，之後猶會使加更多資料。",
    "common.healthHub": "用 HealthHub 登入",
    "common.healthHubComingSoon": "即將開始",
    "common.guidedSetup": "回答幾个簡單問題",
    "common.setupMinutes": "這只需要幾分鐘。",
  },
  yue: {
    "nav.home": "首頁",
    "nav.medications": "藥物",
    "nav.askMei": "問Mei",
    "nav.notifications": "通知",
    "nav.settings": "設定",
    "header.hello": "你好，{name}！",
    "home.today": "今日",
    "home.scheduled": "已安排",
    "home.comingUp": "即將到嚟",
    "home.taken": "已服用",
    "home.iTookIt": "我已經食咗 ✓",
    "home.markTaken": "標記為已服用",
    "home.whatTime": "你係咩時間服用嘅？",
    "home.justNow": "剛先",
    "home.confirm": "確認",
    "home.recorded": "已記錄！做得好 🌟",
    "home.now": "而家",
    "home.refillNeeded": "藥快用完",
    "home.noSchedule": "冇安排嘅藥物。",
    "prescription.count": "{count} 種藥物",
    "prescription.add": "加續藥 / 處方",
    "prescription.empty": "重未有藥物 — 請撳上方「加續藥 / 處方」開始。",
    "prescription.supply": "剩餘藥量",
    "prescription.past": "以前食過嘅藥物",
    "prescription.disclaimer": "請照醫生處方食藥。唔好自行停藥或改藥量。",
    "notifications.header": "來自屋企人同護理團隊嘅訊息",
    "notifications.empty": "重未有護理人員嘅訊息。",
    "settings.voiceAndLanguage": "語音同語言",
    "settings.readAloud": "朗讀回覆",
    "settings.readAloudDesc": "Mei 會將回覆讀出嚟",
    "settings.language": "語言",
    "settings.languageDesc": "Mei 會用呢種語言回覆",
    "ai.chatTab": "同Mei傾",
    "ai.doctorTab": "問醫生",
    "ai.quickHelp": "快速幫手",
    "ai.helpSetup": "幫我設定",
    "ai.languageVoice": "語言同語音",
    "ai.speaking": "講緊",
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.medications": "மருந்துகள்",
    "nav.askMei": "Mei-ஐக் கேளுங்கள்",
    "nav.notifications": "அறிவிப்புகள்",
    "nav.settings": "அமைப்புகள்",
    "header.hello": "வணக்கம், {name}!",
    "home.today": "இன்று",
    "home.scheduled": "திட்டமிடப்பட்டது",
    "home.comingUp": "விரைவில்",
    "home.taken": "எடுக்கப்பட்டது",
    "home.iTookIt": "நான் எடுத்துவிட்டேன் ✓",
    "home.markTaken": "எடுத்ததாக குறிக்கவும்",
    "home.whatTime": "எந்த நேரத்தில் எடுத்தீர்கள்?",
    "home.justNow": "இப்போதே",
    "home.confirm": "உறுதிப்படுத்தவும்",
    "home.recorded": "பதிவு செய்யப்பட்டது! அருமை 🌟",
    "home.now": "இப்போது",
    "home.refillNeeded": "மறுபொருத்தம் விரைவில் தேவை",
    "home.noSchedule": "திட்டமிடப்பட்ட மருந்துகள் இல்லை.",
    "prescription.count": "{count} மருந்துகள்",
    "prescription.add": "மறுபொருத்தம் / மருந்து சேர்க்கவும்",
    "prescription.empty": "இன்னும் மருந்துகள் சேர்க்கப்படவில்லை — மேலே உள்ள “மறுபொருத்தம் / மருந்து சேர்க்கவும்” என்பதைத் தட்டவும்.",
    "prescription.supply": "எஞ்சிய இருப்பு",
    "prescription.past": "முன்பு எடுத்த மருந்துகள்",
    "prescription.disclaimer": "மருந்துகளை எப்போதும் மருத்துவர் பரிந்துரைத்தபடியே எடுத்துக்கொள்ளுங்கள். உங்கள் மருத்துவரை கலந்தாலோசிக்காமல் நிறுத்தவோ மாற்றவோ வேண்டாம்.",
    "notifications.header": "உங்கள் குடும்பத்தினர் மற்றும் பராமரிப்பு குழுவின் செய்திகள்",
    "notifications.empty": "பராமரிப்பாளரிடமிருந்து இன்னும் செய்திகள் இல்லை.",
    "settings.voiceAndLanguage": "குரல் மற்றும் மொழி",
    "settings.readAloud": "குரலில் படிக்கவும்",
    "settings.readAloudDesc": "Mei தனது பதில்களை சத்தமாக படிக்கும்",
    "settings.language": "மொழி",
    "settings.languageDesc": "Mei இந்த மொழியில் பதிலளிக்கும்",
    "ai.chatTab": "Mei-யுடன் அரட்டையடிக்கவும்",
    "ai.doctorTab": "டாக்டரிடம் கேளுங்கள்",
    "ai.quickHelp": "விரைவு உதவி",
    "ai.helpSetup": "எனக்கு அமைக்க உதவுங்கள்",
    "ai.languageVoice": "மொழி மற்றும் குரல்",
    "ai.speaking": "பேசுகிறது",
  },
  ms: {
    "nav.home": "Laman Utama",
    "nav.medications": "Ubat",
    "nav.askMei": "Tanya Mei",
    "nav.notifications": "Pemberitahuan",
    "nav.settings": "Tetapan",
    "header.hello": "Halo, {name}!",
    "home.today": "Hari Ini",
    "home.scheduled": "Dijadualkan",
    "home.comingUp": "Akan Datang",
    "home.taken": "diambil",
    "home.iTookIt": "Saya Sudah Ambil ✓",
    "home.markTaken": "Tandakan sebagai diambil",
    "home.whatTime": "Bila anda ambil ubat itu?",
    "home.justNow": "Baru sahaja",
    "home.confirm": "Sahkan",
    "home.recorded": "Direkodkan! Hebat 🌟",
    "home.now": "Sekarang",
    "home.refillNeeded": "Ubat perlu diisi semula tidak lama lagi",
    "home.noSchedule": "Tiada ubat yang dijadualkan.",
    "prescription.count": "{count} ubat",
    "prescription.add": "Tambah isi semula / preskripsi",
    "prescription.empty": "Tiada ubat lagi — ketik “Tambah isi semula / preskripsi” di atas untuk bermula.",
    "prescription.supply": "Baki stok",
    "prescription.past": "Ubat yang lepas",
    "prescription.disclaimer": "Sentiasa ambil ubat mengikut preskripsi doktor. Jangan berhenti atau tukar dos tanpa berunding dengan doktor.",
    "notifications.header": "Mesej daripada keluarga dan pasukan penjagaan",
    "notifications.empty": "Tiada mesej daripada penjaga lagi.",
    "settings.voiceAndLanguage": "Suara & Bahasa",
    "settings.readAloud": "Baca dengan kuat",
    "settings.readAloudDesc": "Mei membacakan balasannya dengan kuat",
    "settings.language": "Bahasa",
    "settings.languageDesc": "Mei menjawab dalam bahasa ini",
    "ai.chatTab": "Bual dengan Mei",
    "ai.doctorTab": "Tanya Doktor",
    "ai.quickHelp": "Bantuan cepat",
    "ai.helpSetup": "Bantu saya sediakan",
    "ai.languageVoice": "Bahasa & suara",
    "ai.speaking": "Bercakap",
  },
};

export function t(language: AppLanguage, key: string, params?: Record<string, string | number>) {
  const value = TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  return Object.entries(params ?? {}).reduce((acc, [k, v]) => acc.replaceAll(`{${k}}`, String(v)), value);
}

export function getLanguageLabel(language: AppLanguage) {
  return LANGUAGE_OPTIONS.find(option => option.id === language)?.label ?? LANGUAGE_OPTIONS[0].label;
}
